apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "yolo-training"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: mcxrj/yolov3:v1
              args: ["--backend", "nccl"]
              resources: 
                limits:
                  nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: mcxrj/yolov3:v1
              args: ["--backend", "nccl"]
              resources: 
                limits:
                  nvidia.com/gpu: 1

