apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "yolov3-ddp-training"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          hostIPC: true
          containers:
            - name: pytorch
              image: mcxrj/yolov3-ddp-training:v5
              imagePullPolicy: "IfNotPresent"
              command:
                - python
                - -m
                - torch.distributed.launch
                - --nproc_per_node=1
                - --nnodes=$(WORLD_SIZE)
                - --node_rank=$(RANK)
                - --master_addr=$(MASTER_ADDR)
                - --master_port=$(MASTER_PORT)
                - train.py
                - --img=320
                - --batch-size=24
                - --epochs=1
                - --data=coco128.yaml
                - --weights=yolov3.pt 
              resources: 
                limits:
                  nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          hostIPC: true
          containers: 
            - name: pytorch
              image: mcxrj/yolov3-ddp-training:v5
              imagePullPolicy: "IfNotPresent"          
              command:
                - python
                - -m
                - torch.distributed.launch
                - --nproc_per_node=1
                - --nnodes=$(WORLD_SIZE)
                - --node_rank=$(RANK)
                - --master_addr=$(MASTER_ADDR)
                - --master_port=$(MASTER_PORT)
                - train.py
                - --img=320
                - --batch-size=24
                - --epochs=1
                - --data=coco128.yaml
                - --weights=yolov3.pt
              resources: 
                limits:
                  nvidia.com/gpu: 1
