apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "yolov3-training"
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          hostIPC: true
          volumes:
            - name: datasets
              nfs:
                server: 130.113.70.172
                path: /mnt/nfs_host/datasets/renjie
            - name: models
              nfs:
                server: 130.113.70.172
                path: /mnt/nfs_host/models/renjie
          containers:
            - name: pytorch
              image: mcxrj/yolov3-ddp-training:v8
              imagePullPolicy: "IfNotPresent"
              command:
                - python
                - train.py
                - --img=640
                - --batch-size=8
                - --epochs=5
                - --data=coco128.yaml
                - --weights=yolov3.pt
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: /usr/src/app/datasets/
                  name: datasets
                - mountPath: /usr/src/app/runs/
                  name: models
